---
apiVersion: v1
kind: Service
metadata:
  name: 
  labels:
    app: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 1
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: 9841/sail-8.3:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
